spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: high-throughput-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 4
logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    kafka: WARN
    org.apache.kafka.clients.consumer.internals: ERROR
    org.apache.kafka.clients.producer.internals: ERROR
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: consumer-service
